# Site settings
title: gunh0's Tech Blog # site title
description: >- # site description
  gunh0's tech blog documenting web technology and security. He shares his learnings based on web technologies and experiences, with a focus on cybersecurity, cloud security automation, and building resilient systems that protect complex cloud environments. Find out more on <a href="https://github.com/gunh0" target="_blank" rel="noopener">@GitHub</a>.
lang: en-US # default lang
timezone: Asia/Seoul # set your timezone
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/gunh0/gunh0.github.io # site repo [optional]
mode: ligth # default theme "dark" | "light"

# Profile settings
author:
  name: gunh0 # author name
  bio: >- # tell to the world
    I am a Security Research Engineer passionate about mastering the tools of 'Development' and the principles of 'Cybersecurity', striving to balance both in perfect harmony. My focus lies in data-driven security, cloud security automation, and building resilient systems that safeguard complex cloud environments.
    Meet me <a href="https://github.com/gunh0" target="_blank" rel="noopener">@github</a>.
  username: gunh0902 # general username
  github: gunh0 # github username
  twitter: "" # twitter username (if not used, leave it empty)
  facebook: gunh0902 # facebook username
  instagram: gunh0ya # Instagram username
  linkedin: linkedin.com/in/gunh0902 # LinkedIn profile URL
  email: devgun@korea.ac.kr # email address
  avatar: /assets/img/avatar.jpg # change with your own avatar

# URL settings
url: "https://klise.now.sh" #
baseurl:
permalink: /:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
